## SC3 {.tabset}

[Single-Cell Consensus Clustering](https://www.nature.com/articles/nmeth.4236) (`SC3`) is a tool for unsupervised clustering of scRNA-seq data.
SC3 achieves high accuracy and robustness by consistently integrating different clustering solutions through a consensus approach
(it calculates clusters for selected numbers of target clusters).

*Cluster stability index* shows how stable each cluster is across the selected range of `k`s.
The stability index varies between 0 and 1, where 1 means that the same cluster appears in every solution for different `k`.

`r scdrake::create_a_link(cluster_sc3_cluster_stability_plots_file, "**PDF with cluster stability plots**", href_rel_start = fs::path_dir(report_html_file))`

The relationships in cluster abundances under different `k`s are visualized in the `clustree` plot below.
Stable clusters across different `k`s can be quickly find as straight or little branched vertical lines.

`r scdrake::create_a_link(cluster_sc3_clustree_file, "**PDF with clustree**", href_rel_start = fs::path_dir(report_html_file))`

`r scdrake::format_used_functions(c("SC3::sc3()", "SC3::sc3_plot_cluster_stability()"))`

```{r, results = "asis"}
res <- scdrake::generate_dimred_plots_clustering_section(
  dimred_plots_clustering_files, dimred_plots_clustering_united_files, "sc3", "sc3", fs::path_dir(report_html_file), 3
)
```
