### Integration sources #######################################################
INTEGRATION_SOURCES:
  - pbmc1k:
      path: "path/to/.drake or path/to/sce.Rds"
      path_type: "drake_cache"
      description: "10x Genomics PBMC 1k dataset"
      hvg_rm_cc_genes: False
      hvg_cc_genes_var_expl_threshold: null
    pbmc3k:
      path: "path/to/.drake or path/to/sce.Rds"
      path_type: "drake_cache"
      description: "10x Genomics PBMC 3k dataset"
      hvg_rm_cc_genes: False
      hvg_cc_genes_var_expl_threshold: null
###############################################################################

### Selection of highly variable genes (HVGs) #################################
HVG_COMBINATION_INT: "hvg_metric"
HVG_SELECTION_INT: "top"
HVG_SELECTION_VALUE_INT: 3000
###############################################################################

### Integration methods #######################################################
## -- Note: you can leave here only one integration method + "uncorrected" (mandatory)
INTEGRATION_METHODS:
  - uncorrected:
      pca_selection_method: "forced"
      pca_forced_pcs: 15
      tsne_perp: 20
      tsne_max_iter: 1000
    rescaling:
      pca_selection_method: "forced"
      pca_forced_pcs: 15
      tsne_perp: 20
      tsne_max_iter: 1000
      integration_params:
        log.base: 2
        pseudo.count: 1
    regression:
      pca_selection_method: "corrected"
      pca_forced_pcs: 15
      tsne_perp: 20
      tsne_max_iter: 1000
      integration_params:
        d: 50
    mnn:
      pca_selection_method: "corrected"
      pca_forced_pcs: 15
      tsne_perp: 20
      tsne_max_iter: 1000
      integration_params:
        k: 20
        prop.k: null
        cos.norm: True
        ndist: 3
        d: 50
        merge.order: null
        auto.merge: True
    harmony:
      pca_selection_method: null
      pca_forced_pcs: null
      tsne_perp: 20
      tsne_max_iter: 1000
      integration_params:
        dims.use: 50
        theta: null
        lambda: null
        sigma: 0.1
        nclust: null
        tau: 0
        block.size: 0.05
        max.iter.harmony: 10
        max.iter.cluster: 20
        epsilon.cluster: 0.00001
        epsilon.harmony: 0.0001
###############################################################################

### Integration diagnostics ###################################################
INTEGRATION_SNN_K: 10
INTEGRATION_SNN_TYPE: "rank"
INTEGRATION_SNN_CLUSTERING_METHOD: "walktrap"
###############################################################################

### Input files ###############################################################
SELECTED_MARKERS_FILE: null
## -- This is an example file bundled with scdrake and copied to project's root on its initialization
# SELECTED_MARKERS_FILE: "selected_markers.csv"
INTEGRATION_REPORT_RMD_FILE: "Rmd/integration/01_integration.Rmd"
###############################################################################

### Output files ##############################################################
INTEGRATION_BASE_OUT_DIR: "01_integration"
INTEGRATION_SELECTED_MARKERS_OUT_DIR: "selected_markers"
INTEGRATION_REPORT_HTML_FILE: "01_integration.html"
###############################################################################

### HTML output parameters ####################################################
INTEGRATION_KNITR_MESSAGE: False
INTEGRATION_KNITR_WARNING: False
INTEGRATION_KNITR_ECHO: False
###############################################################################
