---
title: "scdrake | 02 - Normalization and clustering (simple)"
author: "Jiri Novotny, Jan Kubovciak"
institute: "Laboratory of Genomics and Bioinformatics @ Institute of Molecular Genetics of the ASCR"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    number_sections: false
    theme: "flatly"
    self_contained: true
    code_download: true
    df_print: "paged"
params:
  css_file: !expr here::here("Rmd/common/stylesheet.css")
  drake_cache_dir: !expr here::here(".drake")
date: "`r glue('Document generated: {Sys.Date()}')`"
css: "`r params$css_file`"
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(drake)
if (rlang::is_true(getOption("knitr.in.progress"))) {
  params_ <- scdrake_list(params)
}
drake_cache_dir <- params_$drake_cache_dir

loadd(
  config_main, config_norm_clustering,
  dimred_plots_clustering_files, dimred_plots_clustering_files_out,
  dimred_plots_other_vars_files, dimred_plots_other_vars_files_out,
  selected_markers_plots, selected_markers_plots_files,
  cell_annotation_diagnostic_plots, cell_annotation_diagnostic_plots_files,

  path = drake_cache_dir
)

if (!is_null(selected_markers_plots)) {
  selected_markers_plots_final <- dplyr::bind_cols(
    selected_markers_plots,
    selected_markers_plots_files = selected_markers_plots_files
  )
} else {
  selected_markers_plots_final <- NULL
}
cfg <- config_norm_clustering

## -- Variables for dimred_plots.Rmd child.
dp_dimred_names <- cfg$NORM_CLUSTERING_REPORT_DIMRED_NAMES
dp_clustering_names <- cfg$NORM_CLUSTERING_REPORT_CLUSTERING_NAMES
dp_selected_markers <- selected_markers_plots_final
dp_selected_markers_files_rel_start <- fs::path_dir(cfg$NORM_CLUSTERING_REPORT_HTML_FILE)
dp_dimred_plots_files_rel_start <- fs::path_dir(cfg$NORM_CLUSTERING_REPORT_HTML_FILE)
dp_cell_annotation_diagnostic_plots_rel_start <- fs::path_dir(cfg$NORM_CLUSTERING_REPORT_HTML_FILE)
```

***

```{r, child = here::here("Rmd/common/_header.Rmd")}
```

***

```{r, child = here::here("Rmd/common/dimred_plots.Rmd")}
```

<details>
  <summary class="config">Show input parameters</summary>
  <hr />
  <h4>Main config</h4>

```{r}
print(config_main)
```

  <hr />
  <h4>Normalization and clustering config</h4>

```{r}
print(cfg)
```
  <hr />
</details>

```{r, child = here::here("Rmd/common/_footer.Rmd")}
```
