---
title: "Cluster markers"
description: "How cluster markers are computed in `scdrake`"
date: "`r glue::glue('<sup>Document generated: {format(Sys.time(), \"%Y-%m-%d %H:%M:%S %Z%z</sup>\")}')`"
package: scdrake
output:
  BiocStyle::html_document:
    toc: true
    toc_float: true
vignette: >
  %\VignetteIndexEntry{Cluster markers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---

***

Taken from [OSCA](https://bioconductor.org/books/release/OSCA.basic/marker-detection.html), slightly modified:

> To interpret our clustering results, we identify the genes that drive separation between clusters.
> These marker genes allow us to assign biological meaning to each cluster based on their functional annotation.
> In the most obvious case, the marker genes for each cluster are a priori associated with particular cell types,
> allowing us to treat the clustering as a proxy for cell type identity. The same principle can be applied to discover
> more subtle differences between clusters (e.g., changes in activation or differentiation state) based on the behavior
> of genes in the affected pathways.

> Identification of marker genes is usually based around the retrospective detection of differential expression
> between clusters. Genes that are more strongly DE are more likely to have caused separate clustering of cells
> in the first place. Several different statistical tests are available to quantify the differences in expression
> profiles, and different approaches can be used to consolidate test results into a single ranking of genes for
> each cluster. These choices parametrize the theoretical differences between the various marker detection strategies.

# Used statistical tests

For each cell grouping and gene, three distinct, adjustable statistical tests are computed through `scran::findMarkers()`:

- t-test (`scran::pairwiseTTests()`): test for difference in mean expression.
- [Wilcoxon signed-rank test](https://en.wikipedia.org/wiki/Wilcoxon_signed-rank_test)
  (`scran::pairwiseWilcox()`): test for difference in median expression (roughly speaking).
- Binomial test (`scran::pairwiseBinom()`):
  test the null hypothesis that the proportion of cells expressing a gene is the same between groups.

These tests are performed in a
[pairwise fashion](https://bioconductor.org/books/release/OSCA.basic/marker-detection.html#scoring-markers-by-pairwise-comparisons)
within each grouping, i.e. each level of the grouping is tested against each other.

Example: three pairwise tests of each type are computed for k-means clustering with $k = 3$:

- Cluster 1 vs. Cluster 2
- Cluster 1 vs. Cluster 3
- Cluster 2 vs. Cluster 3

The overall p-values, false discovery rate (FDR) and effect sizes
(log2 fold change (LFC) for t- and binomial test, and Area Under Curve for Wilcoxon test)
are calculated for the cell grouping from its all pairwise tests (`scran::combineMarkers()`).

# Narrowing down the number of cluster markers

A more or less stringent approach can be used to narrow down the number of cluster markers,
based on results from individual pairwise tests. This will also affect the combined p-value and FDR:

- [Looking for any differences](https://bioconductor.org/books/3.12/OSCA/marker-detection.html#looking-for-any-differences):
  for each level (cluster) of a grouping, take top markers by p-value from each pairwise test. This will be shown
  as `Top` column in marker table. Example: the set of all genes with `Top` values of 1 contains the gene with
  the lowest p-value from each comparison.
- [Finding cluster-specific markers](https://bioconductor.org/books/3.12/OSCA/marker-detection.html#finding-cluster-specific-markers):
  a more stringent approach only considering genes that are differentially expressed in all pairwise comparisons
  involving the cluster of interest. For this purpose is used an intersection-union test where the combined
  p-value for each gene is the maximum of the p-values from all pairwise comparisons.
  A gene will only achieve a low combined p-value if it is strongly DE in all comparisons to other clusters.
- [Balancing stringency and generality](https://bioconductor.org/books/3.12/OSCA/marker-detection.html#balancing-stringency-and-generality):
  the Holm-Bonferroni correction is applied on pairwise p-values and the middle-most value is taken as the combined
  p-value. This effectively tests the global null hypothesis that at least 50% of the individual pairwise comparisons
  exhibit no differential expression.

This can be controlled via the `PVAL_TYPE` parameter in `cluster_markers.yaml` config.
See `vignette("stage_cluster_markers")` for details.

# Handling blocking factors

[Blocking factors](https://bioconductor.org/books/3.12/OSCA/marker-detection.html#marker-batch)
(e.g. batch effect, sex differences, cell cycle phases) can be handled by further nesting.
For that, each pairwise test is performed separately in each level of the blocking factor.
Then, p-values from individual levels' tests are combined, and the final combined p-values are obtained by
the method of choice (see above).

This can be controlled via the `BLOCK_COLUMN` parameter in `cluster_markers.yaml` config.
See `vignette("stage_cluster_markers")` for details.
