## -- Comment/uncomment DRAKE_TARGETS below to make specific stage reports. Only one must be uncommented!
## -- But you can specify any target/s you want - you can review the stage vignettes, e.g. vignette("stage_norm_clustering"),
## -- to see the most important targets.

## -- Single-sample pipeline stage reports:
## -- Stage 01_input_qc:
DRAKE_TARGETS: ["report_input_qc"]

## -- Stage 02_norm_clustering:
# DRAKE_TARGETS: ["report_norm_clustering", "report_norm_clustering_simple"]

## -- Integration pipeline stage reports:
## -- Stage 01_integration:
# DRAKE_TARGETS: ["report_integration"]
## -- Stage 02_int_clustering:
# DRAKE_TARGETS: ["report_int_clustering"]

## -- Reports for common stages:
# DRAKE_TARGETS: ["report_cluster_markers"]
# DRAKE_TARGETS: ["report_contrasts"]

## -- All targets:
# DRAKE_TARGETS: null

DRAKE_CACHE_DIR: ".drake"
DRAKE_KEEP_GOING: False
DRAKE_VERBOSITY: 1
DRAKE_LOCK_ENVIR: True
DRAKE_UNLOCK_CACHE: True
DRAKE_FORMAT: "rds"
DRAKE_REBUILD: null

BLAS_N_THREADS: null
RSTUDIO_PANDOC: null
SEED: 100

### Parallelism ###############################################################
DRAKE_PARALLELISM: "loop"
# DRAKE_PARALLELISM: "future"
# DRAKE_PARALLELISM: "clustermq"

DRAKE_CLUSTERMQ_SCHEDULER: "multicore"
DRAKE_N_JOBS: 4
DRAKE_N_JOBS_PREPROCESS: 4
WITHIN_TARGET_PARALLELISM: False
N_CORES: 4
###############################################################################
