### Project information #######################################################
PROJECT_NAME: "PBMC 1k"
PROJECT_DESCRIPTION: "1000 peripheral blood mononuclear cells by 10x Genomics"
INSTITUTE: "Example institute"
LABORATORY: "Example laboratory"
PEOPLE: "Example person 1, Example person 2"
###############################################################################

### Annotation ################################################################
ORGANISM: "human"
ANNOTATION_LIST:
  human: "org.Hs.eg.db"
  mouse: "org.Mm.eg.db"
ENSEMBL_SPECIES: "Homo_sapiens"
###############################################################################

### Input and output files ####################################################
CSS_FILE: "Rmd/common/stylesheet.css"
BASE_OUT_DIR: "output/single_sample"
###############################################################################
