### Cluster markers ###########################################################
CLUSTER_MARKERS_SOURCES_DEFAULTS:
  COMMON_PARAMS:
    PLOT_DIMREDS: ["umap"]
    BLOCK_COLUMN: null
  PARAMS_T:
    LFC_DIRECTION: "up"
    LFC_TEST: 0
    PVAL_TYPE: "any"
    MIN_PROP: null
    STD_LFC: False
    TOP_N_HEATMAP: 10
    TOP_N_WT_HEATMAP: "top"
    TOP_N_PLOT: 5
    TOP_N_WT_PLOT: "top"
  PARAMS_WILCOX:
    LFC_DIRECTION: "up"
    LFC_TEST: 0
    PVAL_TYPE: "any"
    MIN_PROP: null
    STD_LFC: null
    TOP_N_HEATMAP: 10
    TOP_N_WT_HEATMAP: "top"
    TOP_N_PLOT: 5
    TOP_N_WT_PLOT: "top"
  PARAMS_BINOM:
    LFC_DIRECTION: "up"
    LFC_TEST: 0
    PVAL_TYPE: "any"
    MIN_PROP: null
    STD_LFC: null
    TOP_N_HEATMAP: 10
    TOP_N_WT_HEATMAP: "top"
    TOP_N_PLOT: 5
    TOP_N_WT_PLOT: "top"

CLUSTER_MARKERS_SOURCES:
  - markers_cluster_kmeans_kc_4:
      source_column: "cluster_kmeans_kc_4"
      description: "Cluster markers for k-means clustering (k = 4)"
    markers_cluster_sc3_5:
      source_column: "cluster_sc3_5"
      description: "Cluster markers for SC3 (k = 5)"

MAKE_CLUSTER_MARKERS_PLOTS: True
###############################################################################

### Input files ###############################################################
CLUSTER_MARKERS_TABLE_TEMPLATE_RMD_FILE: "Rmd/common/cluster_markers_table_template.Rmd"
CLUSTER_MARKERS_REPORT_RMD_FILE: "Rmd/common/cluster_markers.Rmd"
###############################################################################

### Output files ##############################################################
CLUSTER_MARKERS_BASE_OUT_DIR: "cluster_markers"

CLUSTER_MARKERS_REPORT_HTML_FILE: "cluster_markers.html"
CLUSTER_MARKERS_HEATMAPS_OUT_DIR: "cluster_markers_heatmaps"
CLUSTER_MARKERS_PLOTS_BASE_OUT_DIR: "cluster_markers_plots"
CLUSTER_MARKERS_DIMRED_PLOTS_BASE_OUT_DIR: "cluster_markers_dimred_plots"
CLUSTER_MARKERS_TABLES_OUT_DIR: "cluster_markers_tables"
###############################################################################
