### Contrasts #################################################################
CONTRASTS_SOURCES_DEFAULTS:
  COMMON_PARAMS:
    PLOT_DIMREDS: ["umap"]
    BLOCK_COLUMN: null
  PARAMS_T:
    LFC_TEST: 0
    STD_LFC: False
    TOP_N_HEATMAP: 10
    TOP_N_WT_HEATMAP: "fdr"
    TOP_N_PLOT: 5
    TOP_N_WT_PLOT: "fdr"
  PARAMS_WILCOX:
    LFC_TEST: 0
    STD_LFC: null
    TOP_N_HEATMAP: 10
    TOP_N_WT_HEATMAP: "fdr"
    TOP_N_PLOT: 5
    TOP_N_WT_PLOT: "fdr"
  PARAMS_BINOM:
    LFC_TEST: 0
    STD_LFC: null
    TOP_N_HEATMAP: 10
    TOP_N_WT_HEATMAP: "fdr"
    TOP_N_PLOT: 5
    TOP_N_WT_PLOT: "fdr"

## -- The second item shows how to perform DEA of all cluster pairs.
CONTRASTS_SOURCES:
  - dea_cluster_graph_leiden_r0.8:
      source_column: "cluster_graph_leiden_r0.8"
      description: "DEA of some groups in graph-based clustering (Leiden alg. with r = 0.8)"
      contrasts:
        - target: "2"
          reference: "1"
        - target: "3"
          reference: "2"
          name: "cl3_vs_cl4"
    # dea_cluster_graph_leiden_r0.4:
    #   source_column: "cluster_graph_leiden_r0.4"
    #   description: "DEA of all groups in graph-based clustering (Leiden alg. with r = 0.4) with blocking on batch"
    #   contrasts: "all"

MAKE_CONTRASTS_PLOTS: True
###############################################################################

### Input files ###############################################################
CONTRASTS_TABLE_TEMPLATE_RMD_FILE: "Rmd/common/contrasts_table_template.Rmd"
CONTRASTS_REPORT_RMD_FILE: "Rmd/common/contrasts.Rmd"
# CONTRASTS_TABLE_TEMPLATE_RMD_FILE: "Rmd/common/contrasts_table_template_spatial.Rmd"
# CONTRASTS_REPORT_RMD_FILE: "Rmd/common/contrasts_spatial.Rmd"
###############################################################################

### Output files ##############################################################
CONTRASTS_BASE_OUT_DIR: "contrasts"

CONTRASTS_REPORT_HTML_FILE: "contrasts.html"
CONTRASTS_HEATMAPS_OUT_DIR: "contrasts_heatmaps"
CONTRASTS_PLOTS_BASE_OUT_DIR: "contrasts_plots"
CONTRASTS_DIMRED_PLOTS_BASE_OUT_DIR: "contrasts_dimred_plots"
CONTRASTS_TABLES_OUT_DIR: "contrasts_tables"
###############################################################################
SPATIAL: False
