## Adapted from https://github.com/r-lib/actions/blob/master/.github/workflows/render-readme.yaml
## README.Rmd is re-rendered to README.md
## Docs in gh-pages branch are updated except articles and reference
## (those are triggered by changes in man/ and vignettes/, and treated by check-bioc.yaml workflow)

name: update-docs
on:
  push:
    paths:
      - '_pkgdown.yml'
      - 'README.Rmd'
      - '*.md'
      - 'DESCRIPTION'
      - 'LICENSE'
      - 'NAMESPACE'
      - '.github/**.md'
      - '.github/workflows/update-docs.yaml'
  pull_request:
    paths:
      - '_pkgdown.yml'
      - 'README.Rmd'
      - '*.md'
      - 'DESCRIPTION'
      - 'LICENSE'
      - 'NAMESPACE'
      - '.github/**.md'
      - '.github/workflows/update-docs.yaml'
concurrency:
  group: main

env:
  cache-version: 'cache-v1'

jobs:
  render:
    name: update-docs
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages("remotes")
          saveRDS(remotes::package_deps(c("rmarkdown", "pkgdown"), dependencies = TRUE), ".github/update-docs-depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: "!contains(github.event.head_commit.message, '/nocache')"
        uses: pat-s/always-upload-cache@main
        with:
          path: /home/runner/work/_temp/Library
          key: ${{ env.cache-version }}-biocversion-RELEASE_3_13-r-4.1-${{ hashFiles('.github/update-docs-depends.Rds') }}
          restore-keys: ${{ env.cache-version }}-biocversion-RELEASE_3_13-r-4.1-

      - name: Install R packages
        run: |
          remotes::install_cran(c("rmarkdown", "pkgdown"))
        shell: Rscript {0}

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Run pkgdown
        run: |
          pkgdown::build_home()
          pkgdown::build_news()
        shell: Rscript {0}

      - name: Commit to gh-pages branch
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git remote set-branches --add origin gh-pages
          git fetch origin gh-pages
          git worktree add --track -B gh-pages /tmp/gh-pages origin/gh-pages
          cd /tmp/gh-pages
          git add -A .
          commit_message=$(Rscript -e "cat(pkgdown:::construct_commit_message('.'))")
          git commit --allow-empty -m $commit_message || echo "No changes to commit"
          git remote -v
          git push --force origin HEAD:gh-pages || echo "No commits to push"

      - name: Commit README.md to main branch
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No commits to push"
